import AppKit
import Foundation

/// Hands a captured header to the user's own mail client, pre-addressed and
/// with the file attached.
///
/// The app deliberately does not send anything itself: no credentials ship
/// with it, and nothing leaves the machine until the person reads the draft
/// and presses send.
enum ContributionMailer {
    static let recipient = "miguel@nspx.dev"

    static func compose(attaching dump: URL, drive: Drive, language: Language) -> Bool {
        guard let service = NSSharingService(named: .composeEmail) else { return false }

        service.recipients = [recipient]
        service.subject = "Sigil header dump — \(drive.name) (\(drive.formattedSize))"

        let items: [Any] = [body(for: drive, language: language), dump]
        guard service.canPerform(withItems: items) else { return false }

        service.perform(withItems: items)
        return true
    }

    private static func body(for drive: Drive, language: Language) -> String {
        switch language {
        case .pt:
            return """
                Segue a leitura do cabeçalho de um drive que funciona no PS5.

                Drive: \(drive.name)
                Capacidade: \(drive.formattedSize)

                Se puder, responda dizendo em qual versão de firmware do console este \
                drive está formatado — sem isso não dá para saber a qual layout a \
                amostra corresponde.

                Gerado pelo Sigil.
                """
        case .en:
            return """
                Attached is a header dump from a drive that works in a PS5.

                Drive: \(drive.name)
                Capacity: \(drive.formattedSize)

                If you can, reply with the console firmware version this drive is \
                formatted under — without it there is no way to tell which layout the \
                sample corresponds to.

                Generated by Sigil.
                """
        }
    }
}
