// Windows: no console window behind the app in release builds.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod catalog;
mod drives;
mod patch;

use catalog::CatalogEntry;
use drives::Drive;
use std::path::PathBuf;

const CONTRIBUTION_ADDRESS: &str = "miguel@nspx.dev";

#[tauri::command]
fn list_drives() -> Result<Vec<Drive>, String> {
    drives::list().map_err(|error| error.to_string())
}

#[tauri::command]
async fn load_catalog() -> Result<Vec<CatalogEntry>, String> {
    catalog::load().await.map_err(|error| error.to_string())
}

#[tauri::command]
async fn download_header(entry: CatalogEntry) -> Result<String, String> {
    catalog::download(&entry)
        .await
        .map(|path| path.to_string_lossy().into_owned())
        .map_err(|error| error.to_string())
}

#[tauri::command]
async fn capture_header(drive_id: String, destination: String) -> Result<String, String> {
    let drive = resolve(&drive_id)?;
    let path = PathBuf::from(&destination);

    tauri::async_runtime::spawn_blocking(move || patch::capture(&drive, 64 * 1024 * 1024, &path))
        .await
        .map_err(|error| error.to_string())?
        .map_err(|error| error.to_string())?;

    Ok(destination)
}

#[tauri::command]
async fn write_header(image: String, drive_id: String) -> Result<(), String> {
    let drive = resolve(&drive_id)?;
    let path = PathBuf::from(image);

    tauri::async_runtime::spawn_blocking(move || patch::write(&path, &drive))
        .await
        .map_err(|error| error.to_string())?
        .map_err(|error| error.to_string())
}

/// Opens a pre-addressed draft and reveals the captured file, because `mailto:`
/// cannot carry an attachment on any platform. The app deliberately does not
/// send anything itself: it ships no credentials, and nothing leaves the
/// machine until the person attaches the file and presses send.
#[tauri::command]
fn open_contribution(path: String, drive_name: String, language: String) -> Result<(), String> {
    let (subject, body) = if language == "pt" {
        (
            format!("Sigil header dump — {drive_name}"),
            format!(
                "Segue a leitura do cabecalho de um drive que funciona no PS5.%0D%0A%0D%0A\
                 Drive: {drive_name}%0D%0A%0D%0A\
                 O arquivo esta em: {path}%0D%0A%0D%0A\
                 Se puder, diga em qual versao de firmware do console este drive esta \
                 formatado.%0D%0A%0D%0AGerado pelo Sigil."
            ),
        )
    } else {
        (
            format!("Sigil header dump — {drive_name}"),
            format!(
                "Attached is a header dump from a drive that works in a PS5.%0D%0A%0D%0A\
                 Drive: {drive_name}%0D%0A%0D%0A\
                 The file is at: {path}%0D%0A%0D%0A\
                 If you can, say which console firmware version this drive is formatted \
                 under.%0D%0A%0D%0AGenerated by Sigil."
            ),
        )
    };

    let mailto = format!(
        "mailto:{CONTRIBUTION_ADDRESS}?subject={}&body={}",
        subject.replace(' ', "%20").replace('—', "-"),
        body
    );

    reveal(&path);
    open_url(&mailto)
}

#[tauri::command]
fn contribution_address() -> &'static str {
    CONTRIBUTION_ADDRESS
}

fn resolve(drive_id: &str) -> Result<Drive, String> {
    drives::find(drive_id)
        .map_err(|error| error.to_string())?
        // Re-resolving by id rather than trusting one sent from the frontend
        // means a drive that was unplugged mid-flow fails here instead of
        // resolving to whatever now sits at that path.
        .ok_or_else(|| format!("drive {drive_id} is no longer connected"))
}

fn reveal(path: &str) {
    #[cfg(target_os = "macos")]
    let _ = std::process::Command::new("open")
        .args(["-R", path])
        .spawn();

    #[cfg(target_os = "windows")]
    let _ = std::process::Command::new("explorer")
        .arg(format!("/select,{path}"))
        .spawn();

    #[cfg(target_os = "linux")]
    {
        let parent = std::path::Path::new(path)
            .parent()
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_else(|| ".".into());
        let _ = std::process::Command::new("xdg-open").arg(parent).spawn();
    }
}

fn open_url(url: &str) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    let result = std::process::Command::new("open").arg(url).spawn();

    #[cfg(target_os = "windows")]
    let result = std::process::Command::new("cmd")
        .args(["/C", "start", "", url])
        .spawn();

    #[cfg(target_os = "linux")]
    let result = std::process::Command::new("xdg-open").arg(url).spawn();

    result.map(|_| ()).map_err(|error| error.to_string())
}

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            list_drives,
            load_catalog,
            download_header,
            capture_header,
            write_header,
            open_contribution,
            contribution_address,
        ])
        .run(tauri::generate_context!())
        .expect("error while running Sigil");
}
